### ISSUE TITLE
Sorting the list of rosters based on their data

### ISSUE THREAD

**Issue by mhollink** [avcordaro/mesbg-list-builder-v2024#53]
- [ ] Army List
- [ ] Name
- [ ] Points
- [ ] Units

Maybe the rest?

**Comment by avcordaro** [comment]
Ah nice yeah, this is similar to what I mentioned in issue #50. I think those 4 sorting criteria are fine!

**Comment by mhollink** [comment]
Ooh, whoops. I overlooked that one. 

Will close this one as it is now duplicating an existing issue
