### ISSUE TITLE
Passengers are not updating the Total MWF in Roster Information

### ISSUE THREAD

**Issue by avcordaro** [avcordaro/mesbg-list-builder-v2024#75]
The following passenger options appear to be affected:

Gandalf with Pippin
Eowyn with Merry
Treebeard with Merry & Pippin
Arwen with Frodo (once added from Issue #76)

In all of these cases, the Total MWF does not accurately include their additional points, when their passenger option is selected.

**Comment by mhollink** [comment]
This will also include The white warg and shadowfax.

**Comment by mhollink** [comment]
this issue should be fixed by commit b23068ce690c63ba912b16b4ab1cc0e88147c249
